version: "3.9"

services:
  web:
    image: gradle:6.9.2-jdk11
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ./gradlew bootRun --args='--url="jdbc:mariadb://host.docker.internal:3306/myseattest"'
