spring:
  datasource:
    url: jdbc:h2:mem:myseat
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

---

spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://mariadb:3306/my-seat-mariadb
    username: root
    password: password
