spring:
  datasource:
    url: jdbc:h2:~/data/my-seat-db
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://mariadb:3306/my-seat-mariadb
    username: root
    password: password
