spring:
  datasource:
    url: jdbc:h2:mem:myseat
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secret: "12345678901234567890123456789012"
