spring:
  datasource:
    url: jdbc:h2:mem:myseat
    username: root
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

---

spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://mariadb:3306/my-seat-mariadb
    username: root
    password: password
