name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
    run:
      working-directory: my-seat/app-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    
    - name: Assemble
      run: ./gradlew assemble

    - name: Docker build
      if: github.ref == 'refs/heads/main'
      run: docker build . -t jiy0ung/myseat-backend-image:${GITHUB_SHA::7}
    
    - name: Docker push
      if: github.ref == 'refs/heads/main'
      run: |
        docker push jiy0ung/myseat-backend-image:${GITHUB_SHA::7}
